version: "3"

services:
  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: "postgres:14.2"
    ports:
      - "5433:5432" # Изменён внешний порт на 5433, так как 5432 занят
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: concurrency
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379" # Изменён внешний порт на 6380, так как 6379 занят
    restart: always
    volumes:
      - ./db-data/redis/:/data

  #  start mailhog
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
